# AI分析提示词配置

# AI项目分类提示词
ai_classification_prompt: |
  你是一个专业的AI项目分析师。请分析以下项目信息，判断它是否与人工智能相关。
  
  项目信息：
  - 名称：{name}
  - 描述：{description}
  - 标签：{tags}
  - 编程语言：{language}
  
  请从以下几个维度进行分析：
  1. 项目是否直接使用了AI/ML技术
  2. 项目是否为AI工具或平台
  3. 项目是否解决AI相关问题
  4. 项目描述中是否包含AI相关关键词
  
  请返回JSON格式的结果：
  {{
    "is_ai_related": true/false,
    "confidence_score": 0.0-1.0,
    "reasoning": "判断理由",
    "ai_categories": ["机器学习", "自然语言处理", "计算机视觉", "等"],
    "tech_stack": ["使用的AI技术栈"]
  }}

# 关键词提取提示词
keyword_extraction_prompt: |
  请从以下AI项目描述中提取最重要的技术关键词和趋势词汇。
  
  项目描述：{description}
  
  要求：
  1. 提取5-10个最相关的关键词
  2. 关键词应该反映技术特点和应用领域
  3. 优先提取AI/ML相关的专业术语
  4. 包含新兴技术趋势词汇
  
  请返回JSON格式：
  {{
    "keywords": ["关键词1", "关键词2", ...],
    "categories": {{
      "技术栈": ["技术关键词"],
      "应用领域": ["应用关键词"],
      "趋势词汇": ["趋势关键词"]
    }}
  }}

# 项目总结提示词
project_summary_prompt: |
  请为以下AI项目生成一个简洁而全面的中文总结。
  
  项目信息：
  - 名称：{name}
  - 描述：{description}
  - 星标数：{stars}
  - 编程语言：{language}
  - 最近更新：{updated_at}
  
  总结要求：
  1. 100-200字的简洁描述
  2. 突出项目的AI技术特点
  3. 说明项目的实用价值
  4. 使用通俗易懂的语言
  
  请返回JSON格式：
  {{
    "summary": "项目总结",
    "highlights": ["亮点1", "亮点2", "亮点3"],
    "use_cases": ["应用场景1", "应用场景2"]
  }}

# 趋势分析提示词
trend_analysis_prompt: |
  基于以下AI项目数据，分析当前的技术趋势和热点方向。
  
  项目列表：
  {projects_data}
  
  请分析：
  1. 最热门的AI技术方向
  2. 新兴的技术趋势
  3. 开发者关注的重点领域
  4. 技术发展的变化趋势
  
  请返回JSON格式：
  {{
    "hot_trends": ["热门趋势1", "热门趋势2", ...],
    "emerging_tech": ["新兴技术1", "新兴技术2", ...],
    "focus_areas": ["重点领域1", "重点领域2", ...],
    "trend_analysis": "详细的趋势分析文本"
  }}

# 报告生成提示词
report_generation_prompt: |
  请基于今日收集的AI项目数据，生成一份专业的趋势报告。
  
  数据概览：
  - 总项目数：{total_projects}
  - AI相关项目数：{ai_projects}
  - 主要技术栈：{tech_stacks}
  - 热门关键词：{keywords}
  
  报告结构：
  1. 今日AI项目概览
  2. 技术趋势分析
  3. 热门项目推荐
  4. 发展趋势预测
  
  要求：
  - 专业而易懂的语言
  - 数据驱动的分析
  - 具有前瞻性的见解
  - 适合技术从业者阅读
  
  请生成markdown格式的报告。
